### ISSUE TITLE
Proposal: Automated workflow

### ISSUE THREAD

**Issue by tshino** [codebling/vs-code-default-keybindings#10]
I appreciate making this repository and sharing the knowledge.
It greatly helped me to develop [my vscode extension](https://github.com/tshino/vscode-kb-macro).

The extension requires the default keybindings JSON files to configure itself.
And as you know, it requires much manual work on each OS for each release of vscode.
Since I have no macOS device, I had to ask others to retrieve the latest file.
To mitigate that manual work, as you might have noticed, I have created an automated workflow to retrieve the files.

It runs on GitHub Actions (it's basically free for us, and it supports the three OSs) periodically and creates a PR if any diffs are found.
https://github.com/tshino/vscode-kb-macro/issues/57

So, my proposal is to add an automated workflow to your repository based on mine.
It would need some modification to adapt to your repository and reduce unnecessary dependencies.

If you are interested in this proposal, I would like to create it and make a PR.

**Comment by codebling** [comment]
Yes!! We have been searching for a way to automate the process. I looked at your GitHub Actions and npm script and `generator)/_get_default_keybindings_impl.js`. It looks like you are injecting startup code to retrieve the various keybindings?  

I spent a fair amount of time digging into VS Code's code and debugging it to understand how the keybindings were generated. If I'm understanding your process correctly, this is exactly what I had in mind, but did not have energy to code. 

I would absolutely love a PR. Let me know what you would need from me or how I can help. Thanks for your proposing this!

**Comment by tshino** [comment]
Thank you! I think it will take a couple of days or maybe more.

> It looks like you are injecting startup code to retrieve the various keybindings?

Yes.
There are two JS scripts, [_get_default_keybindings.js](https://github.com/tshino/vscode-kb-macro/blob/main/generator/_get_default_keybindings.js) and [_get_default_keybindings_impl.js](https://github.com/tshino/vscode-kb-macro/blob/main/generator/_get_default_keybindings_impl.js).
One is for launching vscode using [vscode-test](https://github.com/microsoft/vscode-test) which is a testing utility for vscode extensions.
The other is for manipulating the vscode instance from inside it. It runs on the vscode as an extension, thus it has access to [VS Code API](https://code.visualstudio.com/api/references/vscode-api). So it can trigger the `Open Default Keyboard Shortcuts (JSON)` command simply using `vscode.commands.executeCommand` API.
That is how it works.

**Comment by codebling** [comment]
Thanks for explaining! Let me know if there's anything I can do.

**Comment by codebling** [comment]
See also #12. Another PR forthcoming which will link the processing scripts to the Workflows. Closing
