### ISSUE TITLE
Keymap extension to make installation and updating easier

### ISSUE THREAD

**Issue by jbro** [codebling/vs-code-default-keybindings#126]
Hi there,

I just wanted to let you know that I've created a VSCode keymap extension that makes it really easy to use your keybinding files. It can be found [here](https://github.com/jbro/vscode-default-keybindings). 

I made it because I got a bit fed up with another VSCode extension that offers sort of the same functionality, except in three different plugins, one for each OS, and is never updated.

I really like your approach to automatically extract the newest keybindings for each OS, and I've setup some automation that publishes a new version of the extension when ever you update the keybindings here. There is a PR that needs manual merging for now, but I plan to do away with that once I've seen things work a few times.

The extension is pretty simple, it just creates one HUGE keybinding with all the keybindings in it, and then offers configuration option to which are enabled, and whether or not to use the negative list for the current OS.

Let me know what you think? And if you don't like me doing this, I'd be more than happy to offer up a PR to merge the stuff here.

**Comment by codebling** [comment]
That's awesome! 

Have you released your extension in the official VS Code Marketplace, or the [Open VSX Registry](https://open-vsx.org)? Open source versions of VS Code are banned from using the official Marketplace and so must use Open VSX Registry. 

I'm about to leave for a week and expect to spend only very limited time online, but I'll try out your extension as soon as I get a chance!

**Comment by jbro** [comment]
Thanks, 

yes the extension has been release in the official marketplace, I didn't know about Open VSX Registry, but I'll be more than happy releasing it there as well. I'll get on that right away.

Have a nice trip! :)

**Comment by jbro** [comment]
I've published to https://open-vsx.org/extension/jbro/vscode-default-keybindings, and I'm waiting on getting my namespace verified https://github.com/EclipseFdn/open-vsx.org/issues/2770.

**Comment by codebling** [comment]
Sorry for the delay! This is great. I've added a link in the README!

**Comment by jbro** [comment]
Thanks! :D
