### ISSUE TITLE
Can't Press Enter to Insert a newLine

### ISSUE THREAD

**Issue by kuasha420** [codebling/vs-code-default-keybindings#4]
After adding macos.negative and linux keybindings on a Mac VSCode Install. I can't seem to Press enter/return key to go to new line. This error pops up.

`command 'extension.vs_scite_like.onEnterKey' not found`

What could be the issue? 

Cheers.

**Comment by codebling** [comment]
Oh darn. 

Looks like there may be an extension installed that's also trying to bind enter key, is that possible?

**Comment by kuasha420** [comment]
Hey! Thanks for responding so quickly. 

It appears that deleting this line fixes the issue: 

`{ "key": "enter",                 "command": "extension.vs_scite_like.onEnterKey",`

https://github.com/codebling/vs-code-default-keybindings/blob/4f7813884f737dee3490ad2da972e4f74e4040c5/linux.keybindings.json#L1158

I don't have any relevant extension 'vs_scite_like'. Is there a chance vs_scite_like is installed on your setup and it's setting up a binding? The culprit line is on the aforementioned link. 

Regards.

**Comment by codebling** [comment]
Thanks for spotting that!  Sorry about that!  
That line must have been added in the most recent PR. I admittedly didn't check the diffs, as the files were ordered differently so the entire file was different. I'll take a closer look right now.

**Comment by codebling** [comment]
Darn.. Looks like any installed extensions pollute the default keybindings. I didn't think did -- we'll have to recreate the keybindings from a clean system. Sorry about that!

**Comment by kuasha420** [comment]
No need to apologize. It's still infinitely better for me compared to macos keybindings xD

**Comment by codebling** [comment]
Should be resolved now that #5 is merged, sorry for the delay!  You can thank @moltenform for contributing the latest bindings!

**Comment by kuasha420** [comment]
Much love to @moltenform  and you, @codebling ! These keybindings make my life bearable while I'm developing on macos :)
