### ISSUE TITLE
Request: mappings to make Mac act like Windows with NumLock Off

### ISSUE THREAD

**Issue by richardtallent** [codebling/vs-code-default-keybindings#88]
This repo has solved a huge frustration for me (thanks!), since I code during the day on Windows and on my Mac for personal projects, and I strongly prefer Windows' keyboard mappings.

But there is a small gap -- the numeric keypad. NumLock stays off in my world unless I'm very purposefully 10-keying some numeric data (rare). I've been doing this since my first IBM XT clone, before the Inverted "T" arrows were a thing, so it's a hard habit to break - I've been using Macs at home exclusively since 2006 and I'm still not there.

I was able to get the numeric keypad to basically simulate NumLock=off by duplicating the full Windows key mappings in this repo, using regex to replace "up", "down", etc. with their keypad equivalents (`[Numpad8]`, `[Numpad2]`, etc.). I then merged it with the original file and removed duplicate lines (i.e., mappings not associated with these keys).

I think this could be useful to others, so I'd be happy to contribute the final file, but I'm guessing that would subvert the extraction process you're using.

So, instead, I'd like to suggest that a separate Windows version be available that would likewise provide Numpad alternates for each arrow/pgdn/pgup/home/end/insert/delete mapping.

**Comment by moltenform** [comment]
glad the project has been useful for you!

we could have a python file or sh script or similar that uses your regexes to transform the `windows.keybindings.json` file into a `windows_numpad.keybindings.json` file you could use. the script could be in the repo and people could run it as desired. i think this would make the functionality usable for others who want it, as an opt-in for this edge case. that way it wouldn't add clutter or need automation-changes. codebling can weigh in too but those were my thoughts.

**Comment by codebling** [comment]
I have mixed feelings about making a change for this. On the one hand, it's nice to be useful, on the other hand the numpad hack isn't really related to the purpose of this repo, and I don't really see many other people benefiting from it. Maybe a separate repo whose workflows are triggered by this repo? 

@richardtallent can you provide the final file you mentioned? How often do you have to reapply this change?

**Comment by codebling** [comment]
Closing pending feedback from @richardtallent .

**Comment by richardtallent** [comment]
Sorry, been a bit swamped. The "final" file isn't quite final yet -- some things, like tab autocomplete, don't seem to work, so I'm probably going to have to restore my keyboard layout file and start over.

But *mostly*, it is working, and it's a breath of fresh air to actually be productive in VS Code on the Mac. I love my Apple products, been using them exclusively at home since 2006, but code editing has too much muscle memory from my daily work (which is all on Windows).

I may get a chance to do a bit more this weekend.
